server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false   # euraka?
    fetch-registry: false
  server:
    response-cache-update-interval-ms: 10000
